name: onpush
on: [push, workflow_dispatch]
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-versions: 18
      - run: npm ci
      - run: npm lint
      - run: npm build
